Repository libuv/libuv, pull requests merged in 2021-09, with the labels that each got.

#3084 Use standard installation layout
  CMakeLists.txt
Labels: not-stale, pending-CI

#3167 win: Allow UNC path with forward slash
  src/win/process.c
Labels: windows, not-stale, pending-CI

#3259 win: fix uv_fs_event_stop() assert
  src/win/fs-event.c
  test/test-fs-event.c
  test/test-list.h
Labels: windows
