Repository libuv/libuv, pull requests merged in 2021-07, with the labels that each got.

#3005 build,autotools: make sure -fvisibility=hidden is set
  configure.ac
Labels: pending-CI, stale

#3046 illumos: event ports to epoll
  CMakeLists.txt
  Makefile.am
  src/unix/epoll.c
  src/unix/internal.h
  src/unix/linux-core.c
  src/unix/sunos.c
Labels: pending-CI

#3219 unix/tty: UV_TTY_MODE_IO waits for 4 bytes at a time on illumos
  src/unix/tty.c
Labels: pending-CI

#3232 linux: read CPU model information on ppc
  src/unix/linux-core.c
Labels: linux

#3162 darwin: fix uv_barrier race condition
  src/unix/thread.c
Labels: pending-CI

#2986 udp: ensure that suggested_size in alloc_cb of recv_start is 1 max size dgram
  docs/src/udp.rst
  src/unix/udp.c
  src/uv-common.h
  src/win/udp.c
Labels: pending-CI

#3236 mingw: Fix building for ARM/AArch64
  src/win/atomicops-inl.h
Labels: pending-CI

#3152 unix: strnlen is not available on Solaris 10
  src/unix/internal.h
  src/unix/sunos.c
Labels: pending-CI

#3242 sunos: restore use of event ports
  CMakeLists.txt
  Makefile.am
  src/unix/sunos.c
Labels: pending-CI

#3243 sunos: use thread-safe errno
  CMakeLists.txt
Labels: pending-CI

#3246 run test named ip6_sin6_len
  test/test-ip6-addr.c
  test/test-list.h
Labels: test

#3247 [v2] threads,android: use syscall directly for affinity
  src/unix/process.c
  src/unix/thread.c
  test/run-tests.c
  test/test-spawn.c
Labels: pending-CI, v2

#3251 unix: protect fork in uv_spawn from signals
  src/unix/process.c
Labels: pending-CI
