Repository libuv/libuv, pull requests merged in 2021-05, with the labels that each got.

#3154 docs: update read-the-docs version of sphinx
  .readthedocs.yaml
  docs/requirements.txt
Labels: doc

#3085 win: Add cmake STATIC_VCRT option to force /MT build flag
  CMakeLists.txt
Labels: stale

#3006 Revert "Revert "unix,stream: clear read/write states on close/eof""
  CMakeLists.txt
  Makefile.am
  src/unix/stream.c
  src/win/tcp.c
  test/echo-server.c
  test/test-list.h
  test/test-not-readable-nor-writable-on-read-error.c
  test/test-not-readable-on-eof.c
  test/test-not-writable-after-shutdown.c
Labels: stalled

#3076 Document that uv_read_stop always succeeds
  docs/src/stream.rst
Labels: doc

#3040 src: DragonFlyBSD has mgshdr struct too
  src/unix/freebsd.c
  src/unix/internal.h
Labels: not-stale

#2983 Remove _WIN32 guards on threadpool.c
  src/threadpool.c
  src/uv-common.c
Labels: not-stale
