Repository libuv/libuv, pull requests merged in 2022-07, with the labels that each got.

#3643 zos: delay signal handling until after normal i/o
  src/unix/os390.c
Labels: zos

#3624 Enable MSVC_RUNTIME_LIBRARY setting
  CMakeLists.txt
Labels: stale

#3533 [v2] fs: remove incorrect ARRAY_SIZE call
  src/win/fs.c
Labels: v2
