Repository libuv/libuv, pull requests merged in 2022-02, with the labels that each got.

#3406 darwin: bump minimum supported version to 10.15
  SUPPORTED_PLATFORMS.md
Labels: macos

#3395 win: restrict system DLL load paths
  src/win/winapi.c
Labels: windows

#3193 win,errors: remap `ERROR_ACCESS_DENIED` to `UV_EACCES`
  src/win/error.c
Labels: stale

#3271 Fix error C4146 on MSVC
  src/idna.c
Labels: pending-CI

#2817 test: fix benchmark-ping-udp
  test/benchmark-list.h
  test/benchmark-ping-udp.c
Labels: stale

#3053 win: consider a broken pipe a normal EOF
  src/win/fs.c
  test/test-pipe-set-non-blocking.c
Labels: pending-CI

#3475 fix oopsie from #3466
  src/unix/core.c
Labels: pending-CI

#3450 Unbreak build on GNU/Hurd
  CMakeLists.txt
  Makefile.am
  src/strscpy.h
  src/unix/bsd-ifaddrs.c
  src/unix/core.c
  src/unix/fs.c
  src/unix/hurd.c
  src/unix/internal.h
  src/unix/linux-core.c
  src/unix/udp.c
Labels: pending-CI
